#version: '3.9'

services:

  demo-1-postgres-db:
    container_name: demo-1-postgres-db
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network

  demo-1-postgres-adminer:
    container_name: demo-1-postgres-adminer
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:1234:8080"
    depends_on:
      - demo-1-postgres-db
    networks:
      - app-network

  # test-zig-build:
  #   build:
  #     context: ..
  #     dockerfile: docker/zig-build-linux.dockerfile
  #   environment:
  #     - DB_HOST=test-postgres-db
  #   depends_on: 
  #     - test-postgres-db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
